const config = {
  maxWaypoints: 8,
  // rotate x - rotate x degrees clockwise from 0x
  actions: [
    ["tilt", 0],
    ["rotate", 360/7 * 0],
    ["take photo"],
    ["rotate", 360/7 * 1],
    ["take photo"],
    ["rotate", 360/7 * 2],
    ["take photo"],
    ["rotate", 360/7 * 3],
    ["take photo"],
    ["rotate", 360/7 * 4],
    ["take photo"],
    ["rotate", 360/7 * 5],
    ["take photo"],
    ["rotate", 360/7 * 6],
    ["take photo"],

    ["tilt", -30],
    ["rotate", 360/7 * 0],
    ["take photo"],
    ["rotate", 360/7 * 1],
    ["take photo"],
    ["rotate", 360/7 * 2],
    ["take photo"],
    ["rotate", 360/7 * 3],
    ["take photo"],
    ["rotate", 360/7 * 4],
    ["take photo"],
    ["rotate", 360/7 * 5],
    ["take photo"],
    ["rotate", 360/7 * 6],
    ["take photo"],

    ["tilt", -60],
    ["rotate", 360/6 * 0],
    ["take photo"],
    ["rotate", 360/6 * 1],
    ["take photo"],
    ["rotate", 360/6 * 2],
    ["take photo"],
    ["rotate", 360/6 * 3],
    ["take photo"],
    ["rotate", 360/6 * 4],
    ["take photo"],
    ["rotate", 360/6 * 5],
    ["take photo"],

    ["tilt", -90],
    ["take photo"],
  ],
}