const config = {
  maxWaypoints: 7,
  // rotate x - rotate x degrees clockwise from 0x
  actions: [
    ["tilt", 0],
    ["rotate", 360/8 * 0],
    ["take photo"],
    ["rotate", 360/8 * 1],
    ["take photo"],
    ["rotate", 360/8 * 2],
    ["take photo"],
    ["rotate", 360/8 * 3],
    ["take photo"],
    ["rotate", 360/8 * 4],
    ["take photo"],
    ["rotate", 360/8 * 5],
    ["take photo"],
    ["rotate", 360/8 * 6],
    ["take photo"],
    ["rotate", 360/8 * 7],
    ["take photo"],

    ["tilt", -25],
    ["rotate", 360/8 * 0],
    ["take photo"],
    ["rotate", 360/8 * 1],
    ["take photo"],
    ["rotate", 360/8 * 2],
    ["take photo"],
    ["rotate", 360/8 * 3],
    ["take photo"],
    ["rotate", 360/8 * 4],
    ["take photo"],
    ["rotate", 360/8 * 5],
    ["take photo"],
    ["rotate", 360/8 * 6],
    ["take photo"],
    ["rotate", 360/8 * 7],
    ["take photo"],

    ["tilt", -50],
    ["rotate", 360/8 * 0],
    ["take photo"],
    ["rotate", 360/8 * 1],
    ["take photo"],
    ["rotate", 360/8 * 2],
    ["take photo"],
    ["rotate", 360/8 * 3],
    ["take photo"],
    ["rotate", 360/8 * 4],
    ["take photo"],
    ["rotate", 360/8 * 5],
    ["take photo"],
    ["rotate", 360/8 * 6],
    ["take photo"],
    ["rotate", 360/8 * 7],
    ["take photo"],

    ["tilt", -75],
    ["rotate", 360/3 * 0],
    ["take photo"],
    ["rotate", 360/3 * 1],
    ["take photo"],
    ["rotate", 360/3 * 2],
    ["take photo"],

    ["tilt", -90],
    ["take photo"],
  ],
}